language: elixir
elixir:
  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
services:
  - redis-server
otp_release:
  - 17.3
  - 17.4
sudo: false
before_script:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
matrix:
  fast_finish: true
  allow_failures:
    - elixir: 1.0.0
    - elixir: 1.0.1
